name: "Update Currency Exchange Rates"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 1"

jobs:
  update:
    name: Update Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: |
          npm install
      - name: Run
        run: |
          npm run ci
      - uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          message: 'Update exchange rates'
